### PR TITLE
[SINT-496] [SINT-497] Adding Splunk Enums and fixing GET in workflow handler

### PR DESCRIPTION
**Pull request by hernantain**
**What:**  Adding Splunk Enums and fixing GET in workflow handler

**Why**:  GET was broken and enums were missing

https://jira.splunk.com/browse/SINT-496

https://jira.splunk.com/browse/SINT-497

### CODE REVIEW

**Review by tecateca12 — APPROVED** [review]
LGTM !

**Review by marcos-vivar — APPROVED** [review]
LGTM @hernantain! 👍🏽

**Review by manuelramos — APPROVED** [review]
👍

**Review by imonaco — APPROVED** [review]
LGTM!

**Pull request merged**
