### PR TITLE
[ECO-670] added domain value to enum ObservableTypes

### PR DESCRIPTION
**Pull request by manuelramos**
- Added DOMAIN enum back

### CODE REVIEW

**Review by hernantain — APPROVED** [review]
LGTM! Easiest review ever

**Review by marcos-vivar — APPROVED** [review]
LGTM @manuelramos ! 👍🏽 
:shipit:

**Comment by marcos-vivar** [comment]
Hey @manuelramos, @hernantain, and @imonaco:
Do you feel we would need to add a test to validate that **DOMAIN** types are being supported for Indicators instantiation?

**Comment by manuelramos** [comment]
Don't think we need a UT for this kind of change. We do have tests under `test_indicators.py` file already.

**Pull request merged**
